export const COURSE_ROUTINES = [
  { module: 'CrankNicolson', func: 'CrankNicolson', args: 'f, g1, g2, a, b, c, n, m', desc: 'Resuelve la ecuacion del calor, u_{t} = c^2 u_{xx}  para x in [0,a]  y t en [0,b],' },
  { module: 'CuadGaussLegendre', func: 'CuadGaussLegendre', args: 'f, a, b, N', desc: 'Cuadratura de Gauss-Legendre con N nodos en el intervalo [a, b].' },
  { module: 'DifAdelante', func: 'DifAdelante', args: 'f, g1, g2, a, b, c, n, m', desc: 'Resuelve la ecuacion del calor, u_{t} = c^2 u_{xx}  para x in [0,a]  y t en [0,b],' },
  { module: 'Diffin_PVF', func: 'Diffin_PVF', args: 'p, q, r, a, b, alpha, beta, N', desc: 'Resuelve un P.V.F lineal de segundo orden, de la forma' },
  { module: 'DifinHiper', func: 'DifinHiper', args: 'f, g, q1, q2, a, b, c, n, m', desc: 'Resuelve la ecuacion de onda, u_{tt} = c^2 u_{xx}  para x in [0,a]  y t en [0,b],' },
  { module: 'DisparoLin', func: 'DisparoLin', args: 'F1, F2, a, b, alpha, beta, M', desc: 'Resuelve un P.V.F lineal de segundo orden, de la forma' },
  { module: 'Euler', func: 'Euler', args: 'f, a, b, ya, M', desc: 'Resuelve la ecuacion diferencial y(t) = f(t,y), usando el método de Euler' },
  { module: 'GaussSeidel', func: 'GaussSeidel', args: 'A, b, x0, epsilon, max_iter', desc: 'Resuelve el sistema de ecuaciones lineales Ax = b utilizando el método iterativo de Gauss Seidel' },
  { module: 'GraficaSpline', func: 'GraficaSpline', args: 'x,y,S', desc: 'Descripción: Rutina que grafica un spline obtenido para un conjunto de datos' },
  { module: 'Jacobi', func: 'Jacobi', args: 'A, b, x0, epsilon, max_iter', desc: 'Resuelve el sistema de ecuaciones lineales Ax = b utilizando el método iterativo de Jacobi con NumPy.' },
  { module: 'LagrangePol', func: 'LagrangePol', args: 'x_values, y_values', desc: 'Encuentra el polinomio interpolante de Lagrange para un conjunto de datos.' },
  { module: 'MPoisson', func: 'MPoisson', args: 'n', desc: '' },
  { module: 'Minimos_Cuadrados', func: 'Minimos_Cuadrados', args: 'x, y, grado', desc: 'Calcula el polinomio que mejor se ajusta a un conjunto de puntos, de acuerdo con la' },
  { module: 'NeumannM', func: 'NeumannM', args: 'N', desc: '' },
  { module: 'NewtonPol', func: 'NewtonPol', args: 'x_values, y_values', desc: 'Encuentra el polinomio interpolante de Newton para un conjunto de datos.' },
  { module: 'Newton_NL', func: 'Newton_NL', args: 'F, J, x0, tol=1e-6, max_iter=100', desc: 'Resuelve un sistema de ecuaciones no lineales utilizando el método iterativo de' },
  { module: 'Nodos_Cheby', func: 'Nodos_cheby', args: 'f, a, b, n', desc: 'Calcula los nodos de Chebyshev en el intervalo [a, b], a partir de los ceros en [-1,1]' },
  { module: 'Poisson', func: 'Poisson', args: 'g, f1, f2, f3, f4, a, b, c, d, m, n', desc: 'Resuelve el problema de Poisson u_{xx} + u_{yy} = g(x,y) en [a,b] x [c,d],' },
  { module: 'RK2_EulerMod', func: 'RK2_EulerMod', args: 'f, a, b, ya, M', desc: 'Resuelve la ecuacion diferencial y(t) = f(t,y), usando el método de Rnge Kutta 2,' },
  { module: 'RK2_PtoMedio', func: 'RK2_PtoMedio', args: 'f, a, b, ya, M', desc: 'Resuelve la ecuacion diferencial y(t) = f(t,y), usando el método de Rnge Kutta 2,' },
  { module: 'RK3_Heun', func: 'RK3_Heun', args: 'f, a, b, ya, M', desc: 'Resuelve la ecuacion diferencial y(t) = f(t,y), usando el método de Runge' },
  { module: 'RK4', func: 'RK4', args: 'f, a, b, ya, M', desc: 'Resuelve la ecuacion diferencial y(t) = f(t,y), usando el método de Runge' },
  { module: 'RK4_sist', func: 'RK4_sist', args: 'F, a, b, Za, M', desc: 'Resuelve un sistema de ecuaciones diferenciales de primer orden, usando el' },
  { module: 'SplineConoc', func: 'SplineConoc', args: 'X, Y, Sa, Sb', desc: '' },
  { module: 'SplineConst', func: 'SplineConst', args: 'X, Y', desc: '' },
  { module: 'SplineExtra', func: 'SplineExtra', args: 'X, Y', desc: '' },
  { module: 'SplineNat', func: 'SplineNat', args: 'X, Y', desc: 'Spline cúbico natural' },
  { module: 'SplineSuj', func: 'SplineSuj', args: 'X, Y, fpa, fpb', desc: 'Spline cúbico sujeto' },
  { module: 'Taylor', func: 'Taylor', args: 'df, a, b, ya, M', desc: 'Resuelve la ecuacion diferencial y(t) = f(t,y), usando el método de Taylor' },
  { module: 'biseccion', func: 'biseccion', args: 'f, a, b, tol, max_iter', desc: 'Encuentra una raíz aproximada de una función continua f dentro de un intervalo [a, b] usando el método de bisección.' },
  { module: 'newton', func: 'newton', args: 'f, df, p0, tol, max_iter', desc: 'Método de Newton-Raphson' },
  { module: 'newtonAcel', func: 'newton_acel', args: 'f, df, p0, m, tol, max_iter', desc: 'Método de Newton-Raphson acelerado' },
  { module: 'newtonMod', func: 'newton_mod', args: 'f, df, d2f, p0, tol, max_iter', desc: 'Método de Newton-Raphson modificado' },
  { module: 'puntofijo', func: 'punto_fijo', args: 'g, p0, tol, max_iter', desc: 'Punto Fijo' },
  { module: 'simpson', func: 'simpson', args: 'f, a, b, M', desc: 'Aproxima el valor de la integral de una función f en un intervalo acotado [a,b]' },
  { module: 'sor', func: 'SOR', args: 'A, b, x0, w, epsilon, max_iter', desc: 'Resuelve el sistema de ecuaciones lineales Ax = b utilizando el método iterativo de SOR' },
  { module: 'trapecio', func: 'trapecio', args: 'f, a, b, M', desc: 'Aproxima el valor de la integral de una función f en un intervalo acotado [a,b]' },
];
